"""
Tool: save_artifact -- allows agents to save files to their artifacts directory.

Artifacts are files produced by agents during their work -- reports, analysis,
generated images, PDFs, markdown output, etc. They are stored under
shared/agents/<agent-id>/artifacts/ and are accessible via the web UI.

Two usage modes:
  - source_path: stream an existing file on disk (binaries, images, PDFs)
    via the execution backend's cat_file_bytes, which works across sandbox
    (Docker exec + tmpfs), SSH remote, tunnel RPC, and local filesystem.
  - content: write text content (UTF-8) generated by the agent.
"""

from __future__ import annotations

import os
import pwd
import shutil

from backend.tools._workspace import effective_agent_id

BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
_ATTACHMENTS_ROOT = os.path.join(BASE_DIR, 'data', 'attachments')


def _resolve_run_as_user(agent: dict) -> str | None:
    """Return the agent's run_as_user if set and valid, otherwise None."""
    raw = (agent.get('run_as_user') or '').strip()
    if not raw:
        return None
    try:
        pwd.getpwnam(raw)
    except KeyError:
        return None
    return raw


def _chown_to_run_as(path: str, run_as_user: str | None) -> None:
    """Chown a file or directory to the agent's run_as_user."""
    if run_as_user is None:
        return
    try:
        pw = pwd.getpwnam(run_as_user)
        uid = pw.pw_uid
        gid = pw.pw_gid
        os.chown(path, uid, gid)
    except (OSError, KeyError):
        pass


def _artifacts_dir(agent_id: str, run_as_user: str | None = None) -> str:
    d = os.path.join(BASE_DIR, 'shared', 'agents', agent_id, 'artifacts')
    os.makedirs(d, exist_ok=True)
    _chown_to_run_as(d, run_as_user)
    return d


def execute(agent: dict, args: dict) -> dict:
    agent_id = effective_agent_id(agent)
    if not agent_id:
        return {'error': 'Agent ID not found in context'}

    run_as_user = _resolve_run_as_user(agent)

    filename = args.get('filename', '').strip()
    content = args.get('content', '')
    mime_type = args.get('mime_type', '')
    source_path = args.get('source_path', '').strip()

    if not filename:
        return {'error': 'The "filename" parameter is required. Provide a name for the artifact file, e.g. filename="report.md"'}

    # Security: prevent path traversal
    if '/' in filename or '\\' in filename or '..' in filename:
        return {'error': 'Invalid filename: must not contain "/", "\\", or "..". Use a plain basename like "chart.png" or "output.json"'}

    artifacts_dir = _artifacts_dir(agent_id, run_as_user)
    filepath = os.path.join(artifacts_dir, filename)

    try:
        if source_path:
            # --- source_path mode: stream file bytes into artifacts ---
            workplace_id = agent.get('workplace_id')
            sandbox_enabled = agent.get('sandbox_enabled', False)

            if workplace_id:
                from backend.workplaces.manager import workplace_manager

                try:
                    backend = workplace_manager.get_backend(
                        workplace_id, sandbox_enabled=sandbox_enabled
                    )
                except RuntimeError as e:
                    return {'error': f'Workplace error: {str(e)}'}
            elif sandbox_enabled:
                # Sandbox with no workplace: resolve path through execution backend
                from backend.tools.lib.exec_backend import registry as exec_registry
                session_id = agent.get('session_id', 'default')
                backend = exec_registry.get_backend(session_id, agent)
            else:
                # No workplace, no sandbox: use local backend
                from backend.tools.lib.backends.local_backend import LocalBackend
                backend = LocalBackend(session_id=agent.get('session_id', 'default'))

            # Resolve path when the backend has path translation (Docker mount)
            resolved = backend.resolve_path(source_path) if hasattr(backend, 'resolve_path') else source_path

            result = backend.cat_file_bytes(resolved)
            if 'error' in result:
                err_msg = result["error"]

                # Detect file-not-found errors (pattern varies across backends)
                is_not_found = (
                    'file not found' in err_msg.lower() or
                    'no such file' in err_msg.lower() or
                    'not found' in err_msg.lower()
                )

                if is_not_found:
                    # Heuristic: does source_path look like text content
                    # rather than a filesystem path? Common signs:
                    # - contains newlines
                    # - very long (> 512 chars)
                    # - has spaces but no path separators (. / \)
                    looks_like_text = (
                        '\n' in source_path or
                        len(source_path) > 512 or
                        (not any(c in source_path for c in '/.\\') and ' ' in source_path)
                    )

                    if looks_like_text:
                        return {
                            'error': (
                                f'Source file not found. The provided source_path '
                                f'looks like text content rather than a file path. '
                                f'... Did you mean to use the "content" parameter '
                                f'instead of "source_path"?'
                            )
                        }

                    # Legitimate-looking short path — give actionable error
                    return {
                        'error': (
                            f'Source file not found: "{source_path}". '
                            f'Check that the file exists and the path is correct. '
                            f'If you meant to write text content, use the '
                            f'"content" parameter instead of "source_path".'
                        )
                    }

                # Non-file-not-found errors (permission, I/O, etc.)
                return {'error': f'Failed to read source file: {err_msg}'}

            source_bytes = result['bytes']

            # --- Write to artifacts destination ---
            with open(filepath, 'wb') as f:
                f.write(source_bytes)

            _chown_to_run_as(filepath, run_as_user)

            # --- Verify: compare destination size vs source bytes length ---
            dest_size = os.stat(filepath).st_size
            source_len = len(source_bytes)

            warning = None

            # Determine whether to delete the source file.
            # NEVER delete files inside the attachments root — those are
            # managed by the attachment system and may still be needed by
            # read_attachment / future agent turns.
            resolved_real = os.path.realpath(resolved)
            attachments_real = os.path.realpath(_ATTACHMENTS_ROOT)
            is_attachment = resolved_real.startswith(attachments_real + os.sep)

            if is_attachment:
                # Copy-only: source is a user-uploaded attachment; keep it
                pass
            elif dest_size == source_len:
                # Success — delete source file (move behavior)
                delete_result = backend.delete_file(resolved)
                if 'error' in delete_result:
                    warning = f'Source file not deleted after move: {delete_result["error"]}'
            else:
                # Size mismatch — retry once (overwrite destination)
                with open(filepath, 'wb') as f:
                    f.write(source_bytes)

                _chown_to_run_as(filepath, run_as_user)

                dest_size = os.stat(filepath).st_size

                if dest_size == source_len:
                    # Retry succeeded — delete source
                    delete_result = backend.delete_file(resolved)
                    if 'error' in delete_result:
                        warning = f'Source file not deleted after retry: {delete_result["error"]}'
                else:
                    # Retry still mismatched — delete corrupt destination, return error
                    try:
                        os.remove(filepath)
                    except OSError:
                        pass
                    return {
                        'error': (
                            f'Size mismatch after retry: wrote {source_len} bytes '
                            f'but destination has {dest_size} bytes. Source file retained.'
                        )
                    }

            stat = os.stat(filepath)
            response = {
                'result': 'Artifact saved successfully',
                'filepath': filepath,
                'filename': filename,
                'size': stat.st_size,
            }
            if warning:
                response['warning'] = warning
            return response

        else:
            # --- content mode: write text (UTF-8) ---
            if not content:
                return {'error': 'No data provided. Use "content" for text output (e.g. content="# My Report\\n...") or "source_path" for an existing file on disk (e.g. source_path="/workspace/output.png").'}
            # Normalise smart quotes in text mode artifacts
            from backend.normalizer import normalize_code_quotes
            content = normalize_code_quotes(content)
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(content)

            _chown_to_run_as(filepath, run_as_user)

        stat = os.stat(filepath)
        return {
            'result': 'Artifact saved successfully',
            'filepath': filepath,
            'filename': filename,
            'size': stat.st_size,
        }
    except Exception as e:
        return {'error': f'Failed to save artifact "{filename}": {str(e)}'}
