#!/usr/bin/env python3
"""
build_css.py — Concatenate project CSS sources into static/css/evonic.css.

Usage:
    python3 scripts/build_css.py

Processes files in load order, strips block comments, and writes a single
output file.  Third-party files (tailwind.css) are excluded.
"""

import re
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_FILE = os.path.join(ROOT, 'static', 'css', 'evonic.css')

# Load order matches the <link> order in base.html
SOURCES = [
    'static/style.css',
    'static/css/recap-prose.css',
    'static/css/agent-sidebar.css',
]

_RE_BLOCK_COMMENT = re.compile(r'/\*.*?\*/', re.DOTALL)
_RE_BLANK_LINES = re.compile(r'\n{3,}')


def process(path: str) -> str:
    with open(path, encoding='utf-8') as f:
        src = f.read()
    src = _RE_BLOCK_COMMENT.sub('', src)
    src = _RE_BLANK_LINES.sub('\n\n', src)
    return src.strip()


def build():
    parts = []
    for rel in SOURCES:
        path = os.path.join(ROOT, rel)
        if not os.path.exists(path):
            print(f'ERROR: missing {path}', file=sys.stderr)
            sys.exit(1)
        processed = process(path)
        label = rel
        parts.append(f'/* ── {label} {"─" * (60 - len(label))} */\n\n{processed}')
        print(f'  processed {rel} ({len(processed):,} chars)')

    body = '\n\n\n'.join(parts)
    output = (
        '/* evonic.css — auto-generated by scripts/build_css.py\n'
        ' * Source files: ' + ', '.join(SOURCES) + '\n'
        ' * Do not edit this file directly; edit the source files and re-run the script.\n'
        ' */\n\n'
        + body + '\n'
    )

    with open(OUT_FILE, 'w', encoding='utf-8') as f:
        f.write(output)

    size_kb = os.path.getsize(OUT_FILE) / 1024
    print(f'\nWrote {OUT_FILE} ({size_kb:.1f} KB)')


if __name__ == '__main__':
    print(f'Building evonic.css...')
    build()
